/* Autogenerated by png2wx.pl on Mon May 23 13:54:18 2011 */
#ifndef ICONS_H
#define ICONS_H 1

#include <wx/wxprec.h>
#ifndef WX_PRECOMP
#include <wx/wx.h>
#endif

#include <wx/filename.h>
#include <wx/mstream.h>

extern void initialize_images(void);

extern wxBitmap *_img_vdr_pi;
extern wxBitmap *_img_vdr_play;
extern wxBitmap *_img_vdr_record;

#ifdef PLUGIN_USE_SVG
   extern wxString _svg_vdr_pi;
   extern wxString _svg_vdr_play;
   extern wxString _svg_play_rollover;
   extern wxString _svg_play_toggled;
   extern wxString _svg_vdr_record;
   extern wxString _svg_record_rollover;
   extern wxString _svg_record_toggled;
#endif

#endif /* ICONS_H */
